jobs:

- job: WebApp
  displayName: 'Build Web App'
  pool:
    name: Hosted VS2017
    demands: java
  
  variables:
    BuildConfiguration: release
  
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/WebApp.csproj'
  
  - powershell: |
     Write-Host "Hello World"
     
     $paths = Get-ChildItem -include *.csproj -Recurse
     foreach($pathobject in $paths) 
     {
         $path = $pathobject.fullname
         $doc = New-Object System.Xml.XmlDocument
         $doc.Load($path)
         $child = $doc.CreateElement("ProjectGuid")
         $child.InnerText = [guid]::NewGuid().ToString().ToUpper()
         $node = $doc.SelectSingleNode("//Project/PropertyGroup")
         $node.AppendChild($child)
         $doc.Save($path)
     }
    workingDirectory: WebApp
    displayName: 'PS : Add Project GUID'
  
  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: SonarCloud
      organization: houssemdellai
      projectKey: WebAppWithDatabaseDemo
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/WebApp.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*UnitTest*.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
  
  - task: SonarCloudAnalyze@1
    displayName: 'Run Code Analysis'
  
  - task: SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact (WebApp.zip)'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: drop

- job: Database
  displayName: 'Build Database'
  pool:
    name: Hosted VS2017
    demands: msbuild

  steps:
  - task: MSBuild@1
    displayName: 'Build solution WebApp.Database.sqlproj'
    inputs:
      solution: WebApp.Database/WebApp.Database.sqlproj
      msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact (Dacpac)'
    inputs:
      ArtifactName: dacpac

- job: Selenium
  displayName: 'Build UI Tests'
  pool:
    name: Hosted VS2017
    demands: msbuild

  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.3.0'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: WebAppWithDatabase.sln

  - task: MSBuild@1
    displayName: 'Build project SeleniumUiTests.csproj'
    inputs:
      solution: SeleniumUiTests/SeleniumUiTests.csproj
      msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: UI-Test'
    inputs:
      ArtifactName: 'UI-Test'

- job: Infrastructure
  displayName: 'Copy Infrastructure files'
  pool:
    name: Hosted VS2017
  steps:
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ARM templates'
    inputs:
      PathtoPublish: AzureResourceGroupDeployment
      ArtifactName: arm

- job: Dev
  displayName: 'Deploy to Dev'
  dependsOn: 
  - Infrastructure
  - WebApp

  variables:
    Parameters.ConnectedServiceName: 'Microsoft Azure Sponsorship (5a56fb34-f1c5-4669-9412-4592bb81a2cf)' # couldn't be referenced
    ResourceGroupName: '$(Prefix)-$(Release.EnvironmentName)-$(UniqueId)-RG'
    Database.Admin: 'houssem'
    Database.Password: '@Aa123456'
    Database.Name: 'EmployeesDB'
    WebAppName: '$(Prefix)-$(Release.EnvironmentName)-$(UniqueId)'
    SqlServerName: '$(Prefix)-sql-$(Release.EnvironmentName)-$(UniqueId)'
    Prefix: 'tunis'
    Release.EnvironmentName: 'dev'
    UniqueId: '1280' #'$(Build.BuildId)'

  steps:
  - checkout: none
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: arm
      downloadPath: $(System.DefaultWorkingDirectory)

  - task: CmdLine@2
    inputs:
      script: 'ls'

  - task: AzureResourceGroupDeployment@2
    displayName: 'Validate ARM template'
    enabled: 'true'
    inputs:
      azureSubscription: 'Microsoft Azure Sponsorship (5a56fb34-f1c5-4669-9412-4592bb81a2cf)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(ResourceGroupName)'
      location: 'West Europe'
      templateLocation: 'Linked artifact'
      csmFile: '$(System.DefaultWorkingDirectory)/**/arm/WebSiteSQLDatabase.json'
      csmParametersFile: '$(System.DefaultWorkingDirectory)/**/arm/WebSiteSQLDatabase.parameters.json'
      overrideParameters: '-hostingPlanName "houssemdellai-service-plan" -skuName "F1" -skuCapacity 1 -administratorLogin $(Database.Admin) -administratorLoginPassword $(Database.Password) -databaseName $(Database.Name) -collation "SQL_Latin1_General_CP1_CI_AS" -edition "Basic" -maxSizeBytes "1073741824" -requestedServiceObjectiveName "Basic" -webSiteName $(WebAppName) -sqlserverName $(SqlServerName)'
      deploymentMode: Validation

  - task: AzureResourceGroupDeployment@2
    displayName: 'Create Or Update Resource Group'
    enabled: 'true'
    inputs:
      azureSubscription: 'Microsoft Azure Sponsorship (5a56fb34-f1c5-4669-9412-4592bb81a2cf)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(ResourceGroupName)'
      location: 'West Europe'
      templateLocation: 'Linked artifact'
      csmFile: '$(System.DefaultWorkingDirectory)/**/arm/WebSiteSQLDatabase.json'
      csmParametersFile: '$(System.DefaultWorkingDirectory)/**/arm/WebSiteSQLDatabase.parameters.json'
      overrideParameters: '-hostingPlanName "houssemdellai-service-plan" -skuName "F1" -skuCapacity 1 -administratorLogin $(Database.Admin) -administratorLoginPassword $(Database.Password) -databaseName $(Database.Name) -collation "SQL_Latin1_General_CP1_CI_AS" -edition "Basic" -maxSizeBytes "1073741824" -requestedServiceObjectiveName "Basic" -webSiteName $(WebAppName) -sqlserverName $(SqlServerName)'
      deploymentMode: Complete

  - task: DownloadBuildArtifacts@0    
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      itemPattern: '**/WebApp.zip'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureRmWebAppDeployment@3
    displayName: 'Deploy Web App to Azure App Service'
    enabled: 'true'
    inputs:
      azureSubscription: 'Microsoft Azure Sponsorship (5a56fb34-f1c5-4669-9412-4592bb81a2cf)'
      appType: 'webApp'
      WebAppName: '$(WebAppName)'
      TakeAppOfflineFlag: true
      JSONFiles: '**/appsettings.json'




 



